// Counter
export const INCREMENT = 'INCREMENT';

// Articles
export const FILTER_SELECT_ARTICLE = 'FILTER_SELECT_ARTICLE';
export const FILTER_DATE_ARTICLE = 'FILTER_DATE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';